# --------------------
# 公主连结配置参数定义
# --------------------

# ==================== Pcr ====================

Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [true, false]
  NextRun: 2020-01-01 00:00:00
  Command: Pcr
  SuccessInterval:
    value: 0
    display: hide
  FailureInterval:
    value: 120
    display: hide
  ServerUpdate:
    value: 00:00
    display: hide

Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: auto
    option: [auto]
  ScreenshotMethod:
    value: auto
    option: [auto, ADB, DroidCast_raw, NemuIpc]
  ControlMethod:
    value: auto
    option: [auto, ADB, MaaTouch]
  AdbRestart: true
